git commit -m  "Designed counter and number guessing game using ViewM…
dilaefendioglu/Mobillium-Task3 pull request #1
Opened 2024-08-12 12:17 UTC by dilaefendioglu

Designed counter and number guessing game using ViewModel

2024-08-13 06:21 UTC, TamerSarioglu requested changes
Dila eline sağlık. Bir kaç yorumumum var bunun üzerinde tüm .xml layoutlarında bir formatlama lazım. windows -> ctrl + a yapıp hepsini seçtikten sonra ctrl + alt + L yapılmalı.

2024-08-13 06:21 UTC, TamerSarioglu commented on app/build.gradle.kts
> +
alt+enter ya da mac kullanıyorsan option+enter ile önerilen .toml dosyasına ekleyebiliriz.

2024-08-13 06:21 UTC, TamerSarioglu commented on app/src/main/java/com/dilaefendioglu/interntasks_3a/MainActivity.kt
> +
gereksiz boşlukları silebiliriz.

2024-08-13 06:21 UTC, TamerSarioglu commented on app/src/main/java/com/dilaefendioglu/interntasks_3a/counter/SimpleFragment.kt
> +
viewBinding burada kullanılmamış. Kullanılmalı.

2024-08-13 06:21 UTC, TamerSarioglu commented on app/src/main/java/com/dilaefendioglu/interntasks_3a/counter/SimpleFragment.kt
> +        switchView.setOnCheckedChangeListener { _, isChecked ->
ViewModel switch off konumdayken de state korunuyor ve sayı aynı kalıyor. Bu bir bug. Düzeltilmeli

2024-08-13 06:21 UTC, TamerSarioglu commented on app/src/main/java/com/dilaefendioglu/interntasks_3a/counter/SimpleViewModel.kt
> +    }
fonksiyonlar arası en az. 1 boşluk olmalı.

2024-08-13 06:21 UTC, TamerSarioglu commented on app/src/main/java/com/dilaefendioglu/interntasks_3a/game/DetailFragment.kt
> +        val randomNumber = arguments?.getInt("randomNumber")
Hard coded string olmamalı. Constant object açılıp oradan alınmalı.

2024-08-13 06:21 UTC, TamerSarioglu commented on app/src/main/java/com/dilaefendioglu/interntasks_3a/game/GuessNumberFragment.kt
> +
Buttona tıkladığımda text'e buttonun numarası gelmiyor. Bu bir bug. Düzeltilmeli

2024-08-14 07:20 UTC, TamerSarioglu approved these changes
Eline sağlık. Gayet güzel olmuş. 👍

2024-08-14 13:49 UTC, kerimisoffline approved these changes
Eline sağlık

2024-08-15 07:08 UTC, merged